# Site settings
title: Bubble'S Blog 
header-img: img/home-bg.jpg
email: 460173474@qq.com
copyright_name: guozhaodong
description: "The road to move brick"
baseurl: ""
url: "http://yourdomain.com"
github_username:  guozhaodong
email_username:  460173474@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
